[package]
name = "rustorm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ulid = "1.2.1"
serde_core = "1.0.228"
tokio = { version = "1.49.0", features = ["full"]}
dashmap = "6.1.0"
log = "0.4.29"
